# docker-compose.yml
version: '3.8'

services:
  medical-assistant:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    healthcheck:           # Container health checks
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
    volumes:
      - ./data:/app/data
    restart: unless-stopped